tritlas/community/urls.py
from django.urls import path, include
from community import views
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('',views.home_comm),
    path('post/<id>/',views.one_post),
    path('profile/<id>-user/',views.profile_all),
    path('edit-profile/',views.edit_profile),
    path('new/',views.add_post),
    path('login/',LoginView.as_view(template_name='login.html')),
    path('logout/',LogoutView.as_view()),
    path('signup/',views.register),
    #path('reset/', include('django.contrib.auth.urls')),
    path('reset/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    path('reset/password_reset/', views.password_reset_request, name="password_reset"),

]

tritlas/trips/urls.py
from django.urls import path
from trips import views

urlpatterns = [
    path('',views.one_trip),
    path('<id>/',views.view_trip),
    path('new/add/',views.add_trip),
    path('new/select/',views.select),
]

tritlas/tritlas/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from tritlas import settings
from django.conf.urls import (
handler400, handler403, handler404, handler500
)
from rest_framework.authtoken import views
urlpatterns = [
    path('tritlas-main-admin/', admin.site.urls),
    path('',include('dynamic.urls')),
    path('city/',include('cities.urls')),
    path('trips/',include('trips.urls')),
    path('community/',include('community.urls')),
    re_path('djga/', include('google_analytics.urls')),
    path('api-auth/', include('rest_framework.urls')), #api
    path('api-token-auth/', views.obtain_auth_token), #api
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'dynamic.views.handler_404'

tritlas/community/models.py
from datetime import datetime
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from PIL import Image
import sys
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    tell_us_about_yourself = models.TextField()
    image = models.ImageField(upload_to='users')
    joined_date = models.DateField(auto_now=True,blank=True)
    slug = models.SlugField(null=True,blank=True)

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.first_name)
        super(profile,self).save(*args,**kwargs)
    def __str__(self):
        return '%s' % (self.user)

class post(models.Model):
    user = models.ForeignKey(profile,on_delete=models.CASCADE)
    message = models.TextField(max_length=120)
    date = models.DateTimeField(default=datetime.now, blank=True)
    image = models.ImageField(upload_to='post-imgs')
    comment_counter = models.IntegerField(default=0, blank=True)

    def save(self, *args, **kwargs):
        # Opening the uploaded image
        im = Image.open(self.image)

        output = BytesIO()

        # Resize/modify the image
        #im = im.resize((100, 100))

        # after modifications, save it to the output
        im.save(output, format='JPEG', quality=70)
        output.seek(0)

        # change the imagefield value to be the newley modifed image value
        self.image = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.image.name.split('.')[0], 'image/jpeg',
                                        sys.getsizeof(output), None)

        super(post, self).save()
    
    def __str__(self):
        return str(self.date)

class comment(models.Model):
    in_post = models.ForeignKey(post,on_delete=models.CASCADE)
    user = models.ForeignKey(profile, on_delete=models.CASCADE)
    comment = models.TextField(max_length=120)
    date = models.DateTimeField(default=datetime.now, blank=True)



def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile = profile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile,sender=User)

tritlas/community/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import post, comment, profile


class postForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = post
        fields = ('image','message')

class commentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = ('comment',)

class profileForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['tell_us_about_yourself','image']

class userForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']

tritlas/community/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from trips.models import tripAd, trip
# Create your views here.
from .forms import postForm, commentForm, userForm, profileForm
from .models import post, comment, profile
from django.contrib.auth import login,authenticate

#trip ads


def trip_ad():
    trips = tripAd.objects.all().exclude(published=False)
    try:
        min_ind = trips[0].view_time
        f_id = None
        for i in trips:
            if i.view_time <= min_ind:
                min_ind = i.view_time
                f_id = i.id
        try:
            target = tripAd.objects.get(id=f_id)
            target.view_time += 1
            target.save()
        except:
            target = None
    except:
        target = None
    return target


def home_comm(request):
    all_postss = post.objects.all()
    all_posts = all_postss[::-1]
    paginator = Paginator(all_posts, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'all_posts':all_posts,
        'page_obj':page_obj,
        'nbar': 'community',
    }
    return render(request,'comm.html',context)
def one_post(request,id):
    o_post = post.objects.get(id=id)
    all_commentss = comment.objects.filter(in_post=id)
    all_comments = all_commentss[::-1]
    can_delete = False
    #Ads
    ad = trip_ad()
    if str(o_post.user) == str(request.user):
        can_delete = True
    if request.method == 'POST':
        if 'delete_this' in request.POST:
            o_post.delete()
            form = commentForm()
            return redirect('/community/')
        else:
            form = commentForm(request.POST)
            if form.is_valid():
                ccomment = form.cleaned_data['comment']
                user = request.user
                obj = comment.objects.create(in_post=o_post,user=profile.objects.get(user=user),comment=ccomment)
                obj.save()
                o_post.comment_counter += 1
                o_post.save()
                return redirect('/community/post/%s' %(o_post.id))
    else:
        form = commentForm()
    context = {
        'o_post':o_post,
        'all_comments':all_comments,
        'form':form,
        'can_delete':can_delete,
        'ad':ad,
        'nbar': 'community',
    }
    return render(request,'comm-one-post.html',context)

def edit_profile(request):
    current_user = request.user
    current_img = profile.objects.get(user=request.user)
    user_profile = get_object_or_404(profile,user=current_user)
    if request.method == 'POST':
        user_form = userForm(request.POST,instance=request.user)
        profile_form = profileForm(request.POST,request.FILES,instance=user_profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            new_profile = profile_form.save(commit=False)
            new_profile.save()
            return redirect('/community/profile/%s-user' %(current_user.id))
    else:
        user_form = userForm(instance=request.user)
        profile_form = profileForm(instance=user_profile)
    context = {
        'user_form':user_form,
        'profile_form':profile_form,
        'current_img':current_img,
        'nbar': 'community',
    }
    return render(request,'edit-profile.html',context)
@login_required
def add_post(request):
    if request.method == 'POST':
        form = postForm(request.POST, request.FILES)
        if form.is_valid():
            mess = form.cleaned_data['message']
            img = form.cleaned_data['image']
            obj = post.objects.create(user=profile.objects.get(user=request.user),
                                      message=mess,
                                      image=img)
            obj.save()
            return redirect('/community/post/%s' %(obj.id))
    else:
        form = postForm()
    context = {
        'form':form,
        'nbar': 'community',
    }
    return render(request,'add-post.html',context)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('/community/edit-profile')
    else:
        form = UserCreationForm()
    context = {
        'form':form,
        'nbar': 'community',
    }
    return render(request,'signup.html',context)

def profile_all(request,id):
    edit = False
    user_profile = get_object_or_404(profile,id=id)
    user_tripss = trip.objects.filter(user=id)
    user_trips = user_tripss[::-1]
    user_postss = post.objects.filter(user=id)
    user_posts = user_postss[::-1]
    try:
        if request.user == user_profile.user:
            edit = True
    except:
        edit = False
    try:
        view_msg = request.session.get('pop_msg')
        del request.session['pop_msg']
    except:
        view_msg = False
    context = {
        'user_profile' : user_profile,
        'edit':edit,
        'nbar': 'community',
        'user_trips':user_trips,
        'user_posts':user_posts,
        'view_msg':view_msg
    }
    return render(request,'profile.html',context)
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse

def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                    for user in associated_users:
                        subject = "Password Reset Requested"
                        email_template_name = "password/password_reset_subject.txt"
                        c = {
					    "email":user.email,
					    'domain':'www.tritlas.com',
					    'site_name': 'TriTlas | Egypt',
					    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
					    "user": user,
					    'token': default_token_generator.make_token(user),
					    'protocol': 'http',
					    }
                        email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect ("/community/reset/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="password/password_reset.html", context={"password_reset_form":password_reset_form})

tritlas/community/templates/add-post.html
{% extends 'base.html' %}
{% load static %}
{% block title %} TriTlas | Add Post{% endblock %}
{% block content %}

{% if user.is_authenticated %} <br> <br>
<h1 class="text-center">أضف مشاركة</h1>
        <section class="user-post text-center">


            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <label for="id_image">Upload Image</label>
                    <div class="col-lg-offset-4 col-lg-11">
                    <input class="btn btn-danger"  type="file" name="image" accept="image/*" required="" id="id_image">
                    </div><br>
                        <label for="id_message">Caption</label><br>
                    <textarea name="message" cols="40" rows="10" maxlength="120" required="" id="id_message"></textarea>
                </div>
                <br>
                <button class="btn btn-success" type="submit">Share Your Moment</button>

            </form>

        </section> <br> <br>
{% endif %}
        <style>
            input, select, textarea {
  width: 34%; /* Full width */
  padding: 12px; /* Some padding */
  border: 1px solid #ccc; /* Gray border */
  border-radius: 4px; /* Rounded borders */
  box-sizing: border-box; /* Make sure that padding and width stays in place */
  margin-top: 6px; /* Add a top margin */
  margin-bottom: 16px; /* Bottom margin */
  resize: vertical /* Allow the user to vertically resize the textarea (not horizontally) */
}

/* Style the submit button with a specific background color etc */
input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

/* When moving the mouse over the submit button, add a darker green color */
input[type=submit]:hover {
  background-color: #45a049;
}
        </style>
{% endblock %}

tritlas/community/templates/comm-one-post.html
{% extends 'base.html' %}
{% load static %}
{% block title %} TriTlas {% endblock %}
{% block content %}


        <section class="header-place">
            <div class="container">

               <div class="row text-center">
                    {% if user.is_authenticated %}
                    <h2 style="color:white">مرحباً بك {{user.username}}</h2>
                    <a href="/community/logout" class="btn btn-danger">تسجيل الخروج</a>
                    <a href="/community/new" class="btn btn-success" style="font-size: 20px;">أضف مشاركة</a>
                    {% else %}
                   <h2 style="color:white">أنضم الآن للمجتمع الخاص بنا</h2>
                    <a href="/community/signup" class="btn btn-success">إنشاء حساب</a>
                    <a href="/community/login" class="btn btn-primary">تسجيل الدخول</a>
                    {% endif %}
                    <!-- logout -->
                    <!--

-->
                </div>
            </div>
        </section>
{% if ad %}
<section class="trips-ads text-center">
    <div class="container">
        <div class="card">
  <div class="card-body">
    <h5 class="card-title">رحلة مميزة إلى {{ad.trip_ad.destination}}</h5>
    <p class="card-text">أقضي {{ad.trip_ad.nights}} ليال رائعة فقط وبسعر {{ad.trip_ad.price}} جنية</p>
    <a href="/trips/{{ad.trip_ad.id}}" class="btn btn-primary">أعرف المزيد <span class="glyphicon glyphicon-play-circle"></span></a>
  </div>
</div>
        </div>
    </div>
</section>
{% endif %}

       <section class="comm-posts">
            <div class="container">
                <div class="row">
                    <div class="places-box col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12" style="background-color: #fff">
                        
                        <div class="row" style="margin:1%">
                            <img style="border-radius:50%;width: 50px;height: 50px" src="{% if o_post.user.image %}{{o_post.user.image.url}}{% endif %}">
                            <a href="/community/profile/{{o_post.user.id}}-user" style="text-decoration: none;"> <font size="5px">{{o_post.user}}</font></a>
                            <font size="2px"> - {{o_post.date}}</font>
                        </div>
                        <div class="row" style="margin:1%">
                            <p>{{o_post.message}}</p>
                        </div>
                        <div class="row text-center" style="margin:1%">
                            <img class="img-responsive" src="{{o_post.image.url}}" style="width:70%">
                        </div>
                    </div>
                   
                </div>
                
                <section class="ads">
            
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <a href="/contact"><img class="img-responsive" src="{% static 'img/ad-728-90.png' %}"/></a>
                        </div>
                    </div>
        </section>
                
                
                <div class="comments">
                   <div class="row text-center">
                       {% if can_delete %}<button class="btn btn-danger" type="button" data-toggle="modal" data-target="#exampleModal2">أحذف المنشور</button>{% endif %}
                       <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  أضف تعليق
</button>

                       <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">أضف تعليق</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        {% if user.is_authenticated %}
        <form method="post">
      <div class="modal-body">
          {%csrf_token %}
            {{form}}

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">إغلاف</button>
        <button type="submit" class="btn btn-primary">أضف تعليق الآن</button>
      </div>
             </form>
        {% else %}
        <div class="modal-body">
          قم بتسجيل الدخول أو إنشاء حساب جديد اولاً

      </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">إغلاف</button>
        <a href="/community/login" class="btn btn-primary">تسجيل الدخول</a>
      </div>
        {% endif %}
    </div>
  </div>
</div>


                   </div>
                        <div class="row text-center">
                            <h3>التعليقات</h3>
                       </div>
                        <div class="places-box col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12" style="background-color: #fff">
                            {% for all_comments in all_comments %}
                            <div class="new-comment">
                                <div class="row">
                                    <img style="border-radius:50%;width: 50px;height: 50px" src="{% if all_comments.user.image %}{{all_comments.user.image.url}}{% endif %}">
                                    <a href="/community/profile/{{all_comments.user.id}}-user" style="text-decoration: none;"><font size="5px">{{all_comments.user}}</font></a>
                                    <font size="2px"> - {{all_comments.date}}</font>
                                </div>
                                <div class="row">
                                    <p>{{all_comments.comment}}</p>
                                </div>
                                </div>
                            
                                    <div class="row">
                <div class="about-border justify-content-lg-center"></div>
                </div>
                            {% endfor %}

                        
                    </div>
                    
            </div>
        </section>
           
   

 <!-- Modal delete -->
                   <form method="post">
                       {% csrf_token %}
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">حذف الرحلة</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        هل متأكد من حذف المنشور؟
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">غلق</button>

        <button class="btn btn-danger" type="submit" name="delete_this">حذف الآن</button>

      </div>
    </div>
  </div>
</div></form>
        
        
        {% endblock %}

tritlas/community/templates/comm.html
{% extends 'base.html' %}
{% load static %}
{% block title %} TriTlas {% endblock %}
{% block meta %}
<meta name=”description” content=”شارك تجربتك وتصفح تجارب الأخرين في السفر”>
{% endblock %}
{% block content %}
        
        <!-- slider -->

        <section class="header-place" style="clip-path: circle(614px at center center);">
            <div class="container">
                <div class="row text-center">
                    {% if user.is_authenticated %}
                    <h2 style="color:white">مرحباً بك {{user.username}}</h2>
                    <a href="logout" class="btn btn-danger">تسجيل الخروج</a>
                    <a href="new" class="btn btn-success" style="font-size: 20px;">أضف مشاركة</a>
                    {% else %}
                    <h2 style="color:white">أهلاً بك في مجتمعنا</h2>
                    <a href="signup" class="btn btn-success" style="font-size: 20px;">إنشاء حساب</a>
                    <a href="login" class="btn btn-info" style="font-size: 20px;">تسجيل الدخول</a>
                    {% endif %}
                    <!-- logout -->
                    <!--

-->
                </div>
            </div>
        </section>
        
        <section class="ads">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <a href="/contact"><img class="img-responsive" src="{% static 'img/ad-728-90.png' %}"/></a>
                        </div>
                </div>
            </div>
        </section>
        
       <section class="comm-posts">
            <div class="container">
                <div class="row">
                    {% for all_posts in page_obj %}
                        <div class="bb col-lg-4 col-md-4 col-sm-6 col-xs-12">
                            <div class="card">
                                <a href="post/{{all_posts.id}}" class="no-underline comment-style">
                                      <div class="card-image"><img class="img-responsive" src="{{all_posts.image.url}}" style="width:300px;height:225px"/></div>
                                      <div class="card-text" style="height: 230px;">
                                        <span class="date">{{all_posts.date}}</span>
                                        <h1>
                                           <a href="profile/{{all_posts.user.id}}-user"> <img style="border-radius:50%;width: 50px;height: 50px" class="img-responsive" src="{% if all_posts.user.image %}{{all_posts.user.image.url}}{% endif %}"></a>
                                                                <a href="profile/{{all_posts.user.id}}-user" class="no-underline comment-style" style="color:black"><font size="5px">{{all_posts.user}}</font></a>
                                        </h1>
                                        <p>{{all_posts.message}}</p>
                                      </div>
                                      <div class="card-stats">
                                    <div class="stat border">
                                          <div class="value">{{all_posts.comment_counter}}</div>
                                          <div class="type">comments</div>
                                        </div>
                                        <div class="stat">
                                    <a href="post/{{all_posts.id}}" class="no-underline comment-style">Comments</a>
                                              </div>


                                      </div></a>
                            </div>
                        </div>
                   {% endfor %}
                   
                    
                </div>
                <div class="row text-center">
                        <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-secondary" href="?page=1">&laquo; first</a>
            <a class="btn btn-danger" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="btn btn-secondary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
                    </div>
            </div>
        </section>
{% endblock %}

tritlas/community/templates/edit-profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} TriTlas {% endblock %}
{% block content %}
        
        <!-- slider -->

        <section class="header-place">
            <div class="container">
                <div class="row text-center">
                    <h1 style="color: white">تعديل الحساب الشخصي</h1>
                </div>
                <div class="row text-center">

                </div>
            </div>
        </section>

<section>
    <div class="container">
        <div class="row">
    <form class="text-center" method="post" enctype="multipart/form-data"><br>
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}

        {% if current_img.image %}
        <img src="{{current_img.image.url}}" style="width: 200px;height: 200px;">
        {% endif %}
        <br>
        <button class="btn btn-danger" type="submit">Save</button>
    </form>
            </div>
    </div>
</section>
       
      
           
   
        
        
        
        <style>
            #id_tell_us_about_yourself{
            width:100%;
            }
        </style>
        
        
        
        {% endblock %}

tritlas/community/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} TriTlas | Login{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<meta http-equiv = "refresh" content = "0; url = /community" />
{% else %}
<!--
<form method="post">
        {% csrf_token %}
    {{form}}
    <button type="submit">Login</button>
</form>
-->

<form method="post">
     {% csrf_token %}
  <div class="container-a">
    <h1>تسجيل الدخول</h1>
    <p>برجاء ملئ الفراغات لتسجيل الدخول</p>
    <hr>

    <label for="username"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" id="username" required>

    <label for="password"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" id="password" required>


    <hr>


    <button type="submit" class="registerbtn">تسجيل الدخول</button>
  </div>
  <div class="container signin">
    <p>أسترجع كلمة السر الآن <a href="/community/reset/password_reset/">نسيت كلمة السر؟</a>.</p>
  </div>

  <div class="container signin">
    <p>ليس لديك حساب؟ <a href="/community/signup/">سجل الآن</a>.</p>
  </div>
</form>
<style>
 * {box-sizing: border-box}

/* Add padding to containers */
.container-a {
  padding: 16px;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit/register button */
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity:1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}
</style>


{% endif %}
{% endblock %}