tritlas/trips/urls.py
from django.urls import path
from trips import views

urlpatterns = [
    path('',views.one_trip),
    path('<id>/',views.view_trip),
    path('new/add/',views.add_trip),
    path('new/select/',views.select),
]

tritlas/tritlas/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from tritlas import settings
from django.conf.urls import (
handler400, handler403, handler404, handler500
)
from rest_framework.authtoken import views
urlpatterns = [
    path('tritlas-main-admin/', admin.site.urls),
    path('',include('dynamic.urls')),
    path('city/',include('cities.urls')),
    path('trips/',include('trips.urls')),
    path('community/',include('community.urls')),
    re_path('djga/', include('google_analytics.urls')),
    path('api-auth/', include('rest_framework.urls')), #api
    path('api-token-auth/', views.obtain_auth_token), #api
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'dynamic.views.handler_404'

tritlas/trips/models.py
from django.db import models
from django.contrib.auth.models import User
from django.apps import apps
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from PIL import Image
import sys
# Create your models here.
class trip(models.Model):
    user = models.ForeignKey('community.profile', on_delete=models.CASCADE,blank=True,null=True)
    destination = models.ForeignKey('cities.city',on_delete=models.CASCADE)
    date = models.DateField(default='2020-12-30')
    depart_location = models.CharField(max_length=25)
    depart_time = models.CharField(max_length=6)
    nights = models.IntegerField()
    phone = models.CharField(max_length=18)
    place_of_residence = models.CharField(max_length=20)
    information = models.TextField()
    contact_and_reservation_info = models.TextField()
    price = models.IntegerField()
    active = models.BooleanField(default=True)
    published = models.BooleanField(default=False)
    boost = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user) + " --- " + str(self.destination)


class Images(models.Model):
    post = models.ForeignKey(trip, default=None,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post-image')

    def save(self, *args, **kwargs):
        # Opening the uploaded image
        im = Image.open(self.image)

        output = BytesIO()

        # Resize/modify the image
        #im = im.resize((100, 100))

        # after modifications, save it to the output
        im.save(output, format='JPEG', quality=70)
        output.seek(0)

        # change the imagefield value to be the newley modifed image value
        self.image = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.image.name.split('.')[0], 'image/jpeg',
                                        sys.getsizeof(output), None)

        super(Images, self).save()

class tripAd(models.Model):
    trip_ad = models.ForeignKey(trip, default=None,on_delete=models.CASCADE)
    view_time = models.IntegerField(default=0)
    published = models.BooleanField(default=False)

    def __str__(self):
        return str(self.trip_ad)

tritlas/trips/forms.py
from django import forms

from .models import trip, Images


class tripModel(forms.ModelForm):
    class Meta:
        model = trip
        fields = ('destination','date','depart_location','depart_time','nights','phone','place_of_residence','information','contact_and_reservation_info','price')
class ImagesForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = Images
        fields = ('image',)

tritlas/trips/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.forms import modelformset_factory
from django.shortcuts import render, redirect
from cities.models import city
# Create your views here.
from .forms import tripModel, ImagesForm
from .models import trip, Images
from community.models import profile


def one_trip(request):
    city_list = city.objects.all()
    city_name = False
    trip_boost = False
    trip_list_1 = False
    all_trip_boostt = trip.objects.filter(boost=True).exclude(published=False)
    try:
        all_trip_boost = all_trip_boostt[::-1]
    except:
        all_trip_boost = all_trip_boostt
    if request.GET:
        all_trip_boost = None
        city_name = request.GET.get("city","")
        trip_boostt = trip.objects.filter(destination=city_name,boost=True).exclude(published=False)
        trip_boost = trip_boostt[::-1]
        trip_list_1 = trip.objects.filter(destination=city_name).exclude(boost=True)
        trip_listt = trip_list_1.exclude(published=False)
        trip_list = trip_listt[::-1]
    else:
        trip_listt = trip.objects.all().exclude(boost=True).exclude(published=False)
        try:
            trip_list = trip_listt[::-1]
        except:
            trip_list = trip_listt
    try:
        paginator = Paginator(trip_list, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
    except:
        page_obj = None
    context = {
        'city_list' : city_list,
        'trip_list' : trip_list,
        'trip_boost': trip_boost,
        'all_trip_boost':all_trip_boost,
        'city_name':city_name,
        'nbar': 'trip',
        'page_obj':page_obj
    }
    return render(request,'trip-place.html',context)

def view_trip(request,id):
    trips = trip.objects.get(id=id)
    img = Images.objects.filter(post=id)
    imgs = []
    author = False
    if str(trips.user) == str(request.user):
        author = True
    for i in range(0,len(img)):
        imgs.append(img[i].image)
    if request.method == 'GET':
        if 'stop' in request.GET:
            trips.active = False
            trips.save()
        if 'ret' in request.GET:
            trips.active = True
            trips.save()
        if 'del' in request.GET:
            trips.delete()
            return redirect('/trips/')

    context = {
        'trips':trips,
        'imgs':imgs,
        'nbar': 'trip',
        'author':author
    }
    return render(request,"one-trip.html",context)

@login_required
def add_trip(request):
    ImageFormSet = modelformset_factory(Images,form=ImagesForm, extra=3)
    if request.method == 'POST':
        pForm = tripModel(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,queryset=Images.objects.none())
        if pForm.is_valid() and formset.is_valid():
            f_dist = pForm.cleaned_data['destination']
            f_date = pForm.cleaned_data['date']
            f_depart_loc = pForm.cleaned_data['depart_location']
            f_depart_time = pForm.cleaned_data['depart_time']
            f_nights = pForm.cleaned_data['nights']
            f_phone = pForm.cleaned_data['phone']
            f_stay_place = pForm.cleaned_data['place_of_residence']
            f_info = pForm.cleaned_data['information']
            f_contact = pForm.cleaned_data['contact_and_reservation_info']
            f_price = pForm.cleaned_data['price']
            t = trip(user=profile.objects.get(user=request.user),destination=f_dist,date=f_date,depart_location=f_depart_loc,depart_time=f_depart_time,nights=f_nights,phone=f_phone,place_of_residence=f_stay_place,information=f_info,contact_and_reservation_info=f_contact,price=f_price)
            #post_form = pForm.save(commit=False)
            #post_form.save()
            t.save()
            for form in formset.cleaned_data:
                image = form['image']
                photo = Images(post=t, image=image)
                photo.save()
            request.session['pop_msg'] = True
            return redirect('/community/profile/%s-user' %(request.user.id))
        else:
            print(pForm.errors, formset.errors)
    else:
        pForm = tripModel()
        formset = ImageFormSet(queryset=Images.objects.none())

    context = {'pForm': pForm, 'formset': formset,'nbar': 'trip'}
    return render(request,'add-trip.html',context)

def select(request):
    return render(request,'select.html',context={'nbar': 'trip'})

tritlas/trips/templates/add-trip.html
{% extends 'base.html' %}
{% load static %}
{% block title %} TriTlas {% endblock %}
{% block content %}
        <!-- slider -->

        <section class="header-home" style="clip-path: circle(550px at center center);">
            <div class="container">
               <div class="row">
                   <h1 class="text-center big-word-head">أضف رحلتك</h1>
                </div>
                
            </div>
        </section>
        <section class="add--trip-sec">
            <div class="container">
                <div class="row text-center">
                    <h3>تنوية: بعد إرسال بيانات الرحلة سيقوم فريقنا بمراجعتها وإذا أستوفت <a data-toggle="modal" data-target="#exampleModal">الشروط</a> سيتم قبولها فوراً.</h3>
                    <h4>إذا كنت تريد إضافة إعلان مميز برجاء <a href="/contact">التواصل معنا</a></h4>
                </div>
                <div class="row text-center">
                    <form id="post_form" method="post" enctype="multipart/form-data">
                                           {% csrf_token %}
                        {{pForm.as_p}}

                        {{ formset.management_form }}
                        {% for form in formset %}
                            {{ form }}
                        {% endfor %}


                        <input class="btn btn-danger" type="submit" name="submit" style="margin-bottom:10px" value="Add Your Trip Now" />

                    </form>
                     </div>


<style>
 * {box-sizing: border-box}
#id_date::after{
font-weight: bold;
  color: navy;
content : "Daaate";
}
/* Add padding to containers */
.container-a {
  padding: 16px;
}

/* Full-width input fields */
input[type=text], input[type=number], textarea, select,input[type=file]{
  width: 96%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
input[type=file]
{
color: #fff;
background-color: #d9534f;
border-color: #d43f3a;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit/register button */
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity:1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}
</style>



            </div>
        </section>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">شروط قبول طلب إضافة رحلة</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">

            <div class="col-lg-6 text-center">
                <div class="row">
                <span class="glyphicon glyphicon-ok" style="color:green"></span>
                    </div>
                <div class="row">
                    تأكد من إضافة المعلومات بشكل صحيح
                </div>
            </div>
            <div class="col-lg-6 text-center">
               <div class="row">
                <span class="glyphicon glyphicon-remove" style="color:red"></span>
                    </div>
                <div class="row">
                    لا تضيف روابط خارجية في بيانات الرحلة
                    <br>
                    (متوفر فقط لأصحاب الباقة المميزة)
                </div>
            </div>
            <div class="col-lg-6 text-center">
               <div class="row">
                <span class="glyphicon glyphicon-ok" style="color:green"></span>
                    </div>
                <div class="row">
                    تأكد من إضافة ثلاث صور يتضمن مكان الرحلة او رحلة سابقة
                </div>
            </div>
            <div class="col-lg-6 text-center">
                <div class="row">
                <span class="glyphicon glyphicon-remove" style="color:red"></span>
                    </div>
                <div class="row">
                    لا تقوم بتكرار نشر نفس الرحلة أكثر من مرة واحدة خلال شهر
                </div>
            </div>
            <div class="col-lg-6 text-center">
               <div class="row">
                <span class="glyphicon glyphicon-ok" style="color:green"></span>
                    </div>
                <div class="row">
                    في خانة بيانات الحجز تأكد من كتابة الطرق الصحيحة للحجز سواء رقم هاتف أو وسيلة أخرى
                </div>
            </div>
            <div class="col-lg-6 text-center">
                <div class="row">
                <span class="glyphicon glyphicon-remove" style="color:red"></span>
                    </div>
                <div class="row">
                    لا تقوم بكتابة سعر أقل من السعر الحقيقي للرحلة
                </div>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">غلق</button>
      </div>
    </div>
  </div>
</div>


{% endblock %}

tritlas/trips/templates/one-trip.html
{% extends 'base.html' %}
{% load static %}
{% block title %} TriTlas {% endblock %}
{% block content %}
        {% if not trips.published %}
<meta http-equiv = "refresh" content = "0; url = /dsadasdsadas" />
{% else %}
        <!-- slider -->

        <section class="header-place" style="clip-path: circle(587px at center center);">
            <div class="container">
                <div class="row text-center" style="position: relative;left: 1em;">
                            <h1 style="font-size: 50px;color:#bce4f5">TriTlas</h1>
                        <h2 class="text-center" style="color:white">تنوية: جميع الرحلات المعروضة هي ملك لمنظميها فقط ولا دخل لنا بها</h2>

                </div>
            </div>
        </section>
        
       
       <section class="slider-place">
           <div class="container">
               <div class="row text-center">
                    {% if author %}
                    <form method="get">
                        {% if trips.active %}
                        <button class="btn btn-warning" type="submit" name="stop">إيقاف تفعيل الرحلة</button>
                        {% else %}
                        <button class="btn btn-success" type="submit" name="ret">إعادة تفعيل الرحلة</button>
                        {% endif %}
                    </form>

                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">حذف الرحلة</button>




                   {% endif %}
               </div>
               <div class="row text-center">
                   {% if not trips.active %}
                   <div class="card"><h1>تم إكتمال العدد في هذه الرحلة</h1></div>
                   {% endif %}
               </div>
               <div class"row">
                    <div class="text-center">
                        <h1>الصور</h1>
                        
                    </div>
                </div>
               <div class="row">
                <div class="about-border justify-content-lg-center"></div>
                </div>
               
             

<div class="col-lg-4 col-md-4 col-sm-4" style="margin-bottom: 3%;">
<img id="myImg" src="{{imgs.0.url}}" alt="Not Found" style="width:100%;height:350px">
</div>
<div class="col-lg-4 col-md-4 col-sm-4" style="margin-bottom: 3%;">
<img id="myImg1" src="{{imgs.1.url}}" alt="Not Found" style="width:100%;height:350px">
</div>
<div class="col-lg-4 col-md-4 col-sm-4" style="margin-bottom: 3%;">
<img id="myImg2" src="{{imgs.2.url}}" alt="Not Found" style="width:100%;height:350px">
</div>
<!-- The Modal -->
           <div class="img-cont-modal">
<div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>
</div>
<script>
// Get the modal
var modal = document.getElementById("myModal");

// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById("myImg");
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
  modal.style.display = "block";
  modalImg.src = this.src;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
////////////////////////////////////////
// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById("myImg1");
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
  modal.style.display = "block";
  modalImg.src = this.src;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
//////////////////////////////////////////////////
// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById("myImg2");
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
  modal.style.display = "block";
  modalImg.src = this.src;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
</script>
<style>
body {font-family: Arial, Helvetica, sans-serif;}

#myImg,#myImg1,#myImg2 {
  border-radius: 5px;
  cursor: pointer;
  transition: 0.3s;
}

#myImg:hover,#myImg1:hover,#myImg2:hover {opacity: 0.7;}

/* The Modal (background) */
.img-cont-modal .modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
}

/* Modal Content (image) */
.modal-content {
  margin: auto;
  display: block;
  width: 80%;
  max-width: 700px;
}

/* Caption of Modal Image */
#caption {
  margin: auto;
  display: block;
  width: 80%;
  max-width: 700px;
  text-align: center;
  color: #ccc;
  padding: 10px 0;
  height: 150px;
}

/* Add Animation */
.modal-content, #caption {
  -webkit-animation-name: zoom;
  -webkit-animation-duration: 0.6s;
  animation-name: zoom;
  animation-duration: 0.6s;
}

@-webkit-keyframes zoom {
  from {-webkit-transform:scale(0)}
  to {-webkit-transform:scale(1)}
}

@keyframes zoom {
  from {transform:scale(0)}
  to {transform:scale(1)}
}

/* The Close Button */
.close {
  position: absolute;
  top: 15px;
  right: 35px;
  color: red;
  font-size: 40px;
  font-weight: bold;
  transition: 0.3s;
  opacity: 1;
}

.close:hover,
.close:focus {
  color: #bbb;
  text-decoration: none;
  cursor: pointer;
}

/* 100% Image Width on Smaller Screens */
@media only screen and (max-width: 700px){
  .modal-content {
    width: 100%;
  }
}
</style>

  </section>      
    <section class="info-place">
        <div class="container">
            <div class"row">
                
                    <div class="text-center">
                        <h1>بيانات الرحلة</h1>
                        
                    </div>
                </div>
               <div class="row">
                <div class="about-border justify-content-lg-center"></div>
                </div>
        <div class="row text-center">
            <div class="col-lg-6 col-md-4">
                <p>مشرف الرحلة : <a href="/community/profile/{{trips.user.id}}-user">{{trips.user}}</a></p>
            <p>رقم هاتف مشرف الرحلة : {{trips.phone}}</p>
            <p>نقطة الإنطلاق : {{trips.depart_location}}</p>
            <p>تاريخ الإنطلاق : {{trips.date}}</p>
            </div>
            <div class="col-lg-6 col-md-4">
            <p>ساعة الإنطلاق : {{trips.depart_time}}</p>
            <p>الوجهة : {{trips.destination}}</p>
            <p>مكان الإقامة : {{trips.place_of_residence}}</p>
            <p>عدد الليالي : {{trips.nights}}</p>
                </div>
            <div class="col-lg-6 col-lg-offset-3 text-center col-md-4">
                <p>السعر : {{trips.price}}</p>
            </div>
        </div>
            <div class="row">
                <div class="about-border justify-content-lg-center"></div>
                </div>
            </div>
        </section>
        
        <section class="ads">
            <div class="container">
                <div class="row text-center">
                    <div class="col-lg-6 col-lg-offset-4 col-md-6 col-md-offset-4">
                        <a href=contact.html><img class="img-responsive" src="{% static 'img/ad-336-280.png' %}"/></a>
                        </div>
                </div>
            </div>
        </section>
        
        
        <section class="details-trip">
            <div class="container">
                <div class="row">
                    <div class="text-center">
                        <h1>التفاصيل</h1>
                        
                    </div>
                </div>
                <div class="about-border justify-content-lg-center"></div>
                <div class="row text-center">
                    <p>{{trips.information}}</p>
                </div>
            </div>
        </section>
        <section class="pay-trip">
            <div class="container">
                <div class="row">
                    <div class="text-center">
                        <h1>الحجز والإستعلام</h1>
                        
                    </div>
                </div>
                <div class="about-border justify-content-lg-center"></div>
                <div class="row text-center">
                    <p>
                        {{trips.contact_and_reservation_info}}
                    </p>
                </div>
                <div class="about-border justify-content-lg-center"></div>
            </div>
        </section>
{% endif %}
  <!-- Modal delete -->
                   <form method="get">
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">حذف الرحلة</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        هل متأكد من حذف الرحلة؟
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">غلق</button>

        <button class="btn btn-danger" type="submit" name="del">حذف الرحلة</button>

      </div>
    </div>
  </div>
</div></form>
{% endblock %}

tritlas/trips/templates/select.html
{% extends 'base.html' %}
{% load static %}
{% block title %} TriTlas {% endblock %}
{% block content %}
        <!-- slider -->
        <section class="header-home" style="clip-path: circle(550px at center center);">
            <div class="container">
               <div class="row">
                   <h1 class="text-center big-word-head">TriTlas</h1>
                   <p class="text-center" style="color:white;font-size:40px">أضف رحلتك معنا</p>
                </div>

            </div>
        </section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="card text-center">
                          <div class="card-header" style="background-color: #183751;color:white;font-size: 15px;">
                            أضف إعلان عادي
                          </div>
                          <div class="card-body">

                            <p class="card-text">أضف إعلان لرحلتك يظهر في صفحة الرحلات فقط الآن مجاناً</p>
                            <a href="/trips/new/add" class="btn btn-primary">أضف الآن</a>
                          </div>
                        </div>
            </div>
            <div class="col-lg-6">
                        <div class="card text-center">
                              <div class="card-header" style="background-color: #183751;color:white;font-size: 15px;">
                                أضف إعلان مميز
                              </div>
                              <div class="card-body">

                                <p class="card-text">أضف إعلانك في الباقة المميزة ليظهر لأكبر عدد مكان</p>
                                <a href="/contact" class="btn btn-primary">تواصل معنا الآن</a>
                              </div>
                            </div>
            </div>
        </div>
    </div>
</section>

<section class="features1 cid-qyvcAqZyNq" id="features1-1" data-rv-view="764">




    <div class="container">
        <div class="container">
            <div class="row text-center">
                <h3 style="color: #622727;font-size: 50px;">ماذا نقدم لك في <span style="color:#0e6184">الباقة المميزة</span></h3>
            </div>
                <div class="row">
            <div class="col-lg-4">
                <div class="card">
                        <div class="card-img pb-3">
                            <i class="fa fa-first-order" style="font-size: 50px;padding-top: 10px;color: #1d9dd2;" media-simple="true"></i>
                        </div>
                        <div class="card-box">
                            <h4 style="font-size: 30px;color: #2a626f;">
                                إعلانك يظهر أولاً</h4>
                            <p> أصحاب الباقة المميزة تظهر إعلاناتهم أولاً في الصفحة المخصصة للرحلات لتحظى بنسب ظهور أكثر </p>
                        </div>
                    </div>
            </div>

            <div class="col-lg-4">
                <div class="card">
                        <div class="card-img pb-3">
                    <i class="fa fa-map" style="font-size: 50px;padding-top: 10px;color: #1d9dd2;" media-simple="true"></i>
                </div>
                <div class="card-box">
                    <h4 style="font-size: 30px;color: #2a626f;">
                        إعلانك يظهر في صفحات المدن</h4>
                    <p> أصحاب الباقة المميزة فقط تظهر رحلاتهم في صفحات المدن التي يبحث عنها الزوار لتحظى بنسب ظهور أكثر </p>
                </div></div>
            </div>

            <div class="col-lg-4">
                <div class="card">
                        <div class="card-img pb-3">
                    <i class="fa fa-suitcase" style="font-size: 50px;padding-top: 10px;color: #1d9dd2;" media-simple="true"></i>
                </div>
                <div class="card-box">
                    <h4 style="font-size: 30px;color: #2a626f;">
                        التسويق لرحلتك
                    </h4>
                    <p> أصحاب الباقة المميزة سيتمتعون بنشر رحلاتهم على مواقع التواصل الإجتماعي الخاصة بنا لتحظى بمشاهدات أكثر </p>
                </div></div>
            </div>
           <div class="col-lg-4">
                <div class="card">
                        <div class="card-img pb-3">
                    <i class="fa fa-map" style="font-size: 50px;padding-top: 10px;color: #1d9dd2;" media-simple="true"></i>
                </div>
                <div class="card-box">
                    <h4 style="font-size: 30px;color: #2a626f;">
                        إعلان لرحلتك داخل المجتمع</h4>
                    <p> أصحاب الباقة المميزة يتمتعون بنشر رحلاتهم بشكل دوري داخل منشورات المجتمع الخاصة بنا لتحظى بمشاهدات أكثر </p>
                </div></div>
            </div>

                    <div class="col-lg-4">
                <div class="card">
                        <div class="card-img pb-3">
                    <i class="fa fa-map" style="font-size: 50px;padding-top: 10px;color: #1d9dd2;" media-simple="true"></i>
                </div>
                <div class="card-box">
                    <h4 style="font-size: 30px;color: #2a626f;">
                        دعم فني متواصل</h4>
                    <p> أصحاب الباقة المميزة يتمتعون بدعم فني لإدارة إعلاناتهم وتعديلها وقتما يشاءون بجانب نصائح لكي يظهر إعلانك بأفضل شكل ممكن </p>
                </div></div>
            </div>
                    <div class="col-lg-4">
                <div class="card">
                        <div class="card-img pb-3">
                    <i class="fa fa-map" style="font-size: 50px;padding-top: 10px;color: #1d9dd2;" media-simple="true"></i>
                </div>
                <div class="card-box">
                    <h4 style="font-size: 30px;color: #2a626f;">
                        حملة إعلانية</h4>
                    <p> أصحاب الباقة المميزة يمكنهم طلب إنشاء حملة إعلانية مميزة على صفحات التواصل الإجتماعي المختلفة </p>
                </div></div>
            </div>

</div>


        </div>

    </div>

</section>









        <section class="join-find-bar">
            <div class="container">
            <div class="row  text-center">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 comm-join align-self-center">
                    <h3>أنضم للمجتمع الخاص بنا</h3>
                    <h5>أنضم للمجتمع الخاص بنا وشارك صورك وتفاعل مع صور الأخرين لتتعرف على افضل الأماكن الجديدة</h5>
                    <form action="/community    ">
                    <button class="btn btn-danger">أنضم الآن</button>
                        </form>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 find-jor">
                    <h3>أضف رحلتك</h3>
                    <h5>هل أنت منظم رحلات وتريد إضافة رحلتك؟ أضغط على الزر لمعلومات أكثر</h5>
                    <form action="/trips/new/select">
                        <button class="btn btn-danger">أضف رحلتك</button></form>
                </div>
            </div>
                </div>
        </section>
{% endblock %}